### ISSUE TITLE
Wrong tooltip position for childs element with absolute position

### ISSUE THREAD

**Issue by romanlex** [gilbarbara/react-tooltips#18]
Example https://codesandbox.io/s/7j200nr5l1
Click on Bottom button
![image](https://user-images.githubusercontent.com/3369304/35620556-7f32c588-0692-11e8-8ee0-2483ec9b158d.png)

**Comment by gilbarbara** [comment]
Yeah, that's a problem.
Do you have any idea how to fix this?

Because currently, I'm adding a `ref` and click/hover event handlers in a wrapper that isn't being repositioned when the children have a different `position` than the default...

I'm changing the requirements in 0.3 to accept a single `children` only.

And to fix the positioning the simpler option is to clone the `children` (if there's one) and set `ref` and handlers directly. The drawback is this could override some props of the `children`.

Any ideas?

**Comment by gilbarbara** [comment]
I've found a way to fix this by changing the wrapper style. It worked well, I'll test a bit more and I'll commit soon.

**Comment by gilbarbara** [comment]
fixex in 842cab6b05b0e06194b7da2e88a6dddcdd55b23e and published as 0.2.3
Thanks
