### ISSUE TITLE
Can you add support for change class names

### ISSUE THREAD

**Issue by romanlex** [gilbarbara/react-tooltips#21]
Can you add support for change class names?
Example I want use multiple themes for customize tooltips...all themes described in sass

**Comment by gilbarbara** [comment]
Since all styling is done with an inline `styles` prop it would be better to pass a modified prop instead. Using Sass or CSS you will need to add `!important` to all CSS properties that are already in use to override it.

I was thinking about removing the class altogether because of this limitation but I saw a different approach where the library would skip the `styles` props in the user passes a `class` property but I still not sure if this would be a good thing.

**Comment by gilbarbara** [comment]
Hey,
Support for custom components have been added in #22 

The arrow can be hidden if you want to use our own, but I think it's better to customize it and enjoy the positioning.

**Comment by mahamat** [comment]
Hey, i have a question regarding arrow. I would like to use my own arrow, but struggling to find a way to do it. with hideArrow prop i am able to hide it, but how to implement custom arrow in custom tooltip component ? 
Thank you.
